//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HeXnaModel", "MAPHEX", "MAP", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Landwar.Data.MAP), "HEX", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Landwar.Data.HEX))]

// Original file name:
// Generation date: 2/21/2011 9:38:18 PM
namespace Landwar.Data
{
    
    /// <summary>
    /// There are no comments for HeXnaEntities in the schema.
    /// </summary>
    public partial class HeXnaEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new HeXnaEntities object using the connection string found in the 'HeXnaEntities' section of the application configuration file.
        /// </summary>
        public HeXnaEntities() : 
                base("name=HeXnaEntities", "HeXnaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HeXnaEntities object.
        /// </summary>
        public HeXnaEntities(string connectionString) : 
                base(connectionString, "HeXnaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HeXnaEntities object.
        /// </summary>
        public HeXnaEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "HeXnaEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CREW in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CREW> CREW
        {
            get
            {
                if ((this._CREW == null))
                {
                    this._CREW = base.CreateQuery<CREW>("[CREW]");
                }
                return this._CREW;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CREW> _CREW;
        /// <summary>
        /// There are no comments for HEX in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<HEX> HEX
        {
            get
            {
                if ((this._HEX == null))
                {
                    this._HEX = base.CreateQuery<HEX>("[HEX]");
                }
                return this._HEX;
            }
        }
        private global::System.Data.Objects.ObjectQuery<HEX> _HEX;
        /// <summary>
        /// There are no comments for LNK_SYSTEM_WEAPON in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LNK_SYSTEM_WEAPON> LNK_SYSTEM_WEAPON
        {
            get
            {
                if ((this._LNK_SYSTEM_WEAPON == null))
                {
                    this._LNK_SYSTEM_WEAPON = base.CreateQuery<LNK_SYSTEM_WEAPON>("[LNK_SYSTEM_WEAPON]");
                }
                return this._LNK_SYSTEM_WEAPON;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LNK_SYSTEM_WEAPON> _LNK_SYSTEM_WEAPON;
        /// <summary>
        /// There are no comments for LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT> LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT
        {
            get
            {
                if ((this._LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT == null))
                {
                    this._LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT = base.CreateQuery<LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT>("[LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT]");
                }
                return this._LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT> _LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT;
        /// <summary>
        /// There are no comments for MAP in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MAP> MAP
        {
            get
            {
                if ((this._MAP == null))
                {
                    this._MAP = base.CreateQuery<MAP>("[MAP]");
                }
                return this._MAP;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MAP> _MAP;
        /// <summary>
        /// There are no comments for SYSTEM in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SYSTEM> SYSTEM
        {
            get
            {
                if ((this._SYSTEM == null))
                {
                    this._SYSTEM = base.CreateQuery<SYSTEM>("[SYSTEM]");
                }
                return this._SYSTEM;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SYSTEM> _SYSTEM;
        /// <summary>
        /// There are no comments for SYSTEM_TYPE in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SYSTEM_TYPE> SYSTEM_TYPE
        {
            get
            {
                if ((this._SYSTEM_TYPE == null))
                {
                    this._SYSTEM_TYPE = base.CreateQuery<SYSTEM_TYPE>("[SYSTEM_TYPE]");
                }
                return this._SYSTEM_TYPE;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SYSTEM_TYPE> _SYSTEM_TYPE;
        /// <summary>
        /// There are no comments for TERRAIN in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TERRAIN> TERRAIN
        {
            get
            {
                if ((this._TERRAIN == null))
                {
                    this._TERRAIN = base.CreateQuery<TERRAIN>("[TERRAIN]");
                }
                return this._TERRAIN;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TERRAIN> _TERRAIN;
        /// <summary>
        /// There are no comments for UNIT in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UNIT> UNIT
        {
            get
            {
                if ((this._UNIT == null))
                {
                    this._UNIT = base.CreateQuery<UNIT>("[UNIT]");
                }
                return this._UNIT;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UNIT> _UNIT;
        /// <summary>
        /// There are no comments for UNIT_IN_MAP in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UNIT_IN_MAP> UNIT_IN_MAP
        {
            get
            {
                if ((this._UNIT_IN_MAP == null))
                {
                    this._UNIT_IN_MAP = base.CreateQuery<UNIT_IN_MAP>("[UNIT_IN_MAP]");
                }
                return this._UNIT_IN_MAP;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UNIT_IN_MAP> _UNIT_IN_MAP;
        /// <summary>
        /// There are no comments for WEAPON in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<WEAPON> WEAPON
        {
            get
            {
                if ((this._WEAPON == null))
                {
                    this._WEAPON = base.CreateQuery<WEAPON>("[WEAPON]");
                }
                return this._WEAPON;
            }
        }
        private global::System.Data.Objects.ObjectQuery<WEAPON> _WEAPON;
        /// <summary>
        /// There are no comments for CREW in the schema.
        /// </summary>
        public void AddToCREW(CREW cREW)
        {
            base.AddObject("CREW", cREW);
        }
        /// <summary>
        /// There are no comments for HEX in the schema.
        /// </summary>
        public void AddToHEX(HEX hEX)
        {
            base.AddObject("HEX", hEX);
        }
        /// <summary>
        /// There are no comments for LNK_SYSTEM_WEAPON in the schema.
        /// </summary>
        public void AddToLNK_SYSTEM_WEAPON(LNK_SYSTEM_WEAPON lNK_SYSTEM_WEAPON)
        {
            base.AddObject("LNK_SYSTEM_WEAPON", lNK_SYSTEM_WEAPON);
        }
        /// <summary>
        /// There are no comments for LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT in the schema.
        /// </summary>
        public void AddToLNK_TERRAIN_SYSTEM_TYPE_MOVEMENT(LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT lNK_TERRAIN_SYSTEM_TYPE_MOVEMENT)
        {
            base.AddObject("LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT", lNK_TERRAIN_SYSTEM_TYPE_MOVEMENT);
        }
        /// <summary>
        /// There are no comments for MAP in the schema.
        /// </summary>
        public void AddToMAP(MAP mAP)
        {
            base.AddObject("MAP", mAP);
        }
        /// <summary>
        /// There are no comments for SYSTEM in the schema.
        /// </summary>
        public void AddToSYSTEM(SYSTEM sYSTEM)
        {
            base.AddObject("SYSTEM", sYSTEM);
        }
        /// <summary>
        /// There are no comments for SYSTEM_TYPE in the schema.
        /// </summary>
        public void AddToSYSTEM_TYPE(SYSTEM_TYPE sYSTEM_TYPE)
        {
            base.AddObject("SYSTEM_TYPE", sYSTEM_TYPE);
        }
        /// <summary>
        /// There are no comments for TERRAIN in the schema.
        /// </summary>
        public void AddToTERRAIN(TERRAIN tERRAIN)
        {
            base.AddObject("TERRAIN", tERRAIN);
        }
        /// <summary>
        /// There are no comments for UNIT in the schema.
        /// </summary>
        public void AddToUNIT(UNIT uNIT)
        {
            base.AddObject("UNIT", uNIT);
        }
        /// <summary>
        /// There are no comments for UNIT_IN_MAP in the schema.
        /// </summary>
        public void AddToUNIT_IN_MAP(UNIT_IN_MAP uNIT_IN_MAP)
        {
            base.AddObject("UNIT_IN_MAP", uNIT_IN_MAP);
        }
        /// <summary>
        /// There are no comments for WEAPON in the schema.
        /// </summary>
        public void AddToWEAPON(WEAPON wEAPON)
        {
            base.AddObject("WEAPON", wEAPON);
        }
    }
    /// <summary>
    /// There are no comments for HeXnaModel.CREW in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="CREW")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CREW : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CREW object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="sYSTEM_SPECIALLISM">Initial value of SYSTEM_SPECIALLISM.</param>
        /// <param name="eXPERIENCE">Initial value of EXPERIENCE.</param>
        /// <param name="mAX_NUMBER">Initial value of MAX_NUMBER.</param>
        public static CREW CreateCREW(long id, long sYSTEM_SPECIALLISM, long eXPERIENCE, long mAX_NUMBER)
        {
            CREW cREW = new CREW();
            cREW.ID = id;
            cREW.SYSTEM_SPECIALLISM = sYSTEM_SPECIALLISM;
            cREW.EXPERIENCE = eXPERIENCE;
            cREW.MAX_NUMBER = mAX_NUMBER;
            return cREW;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SYSTEM_SPECIALLISM in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SYSTEM_SPECIALLISM
        {
            get
            {
                return this._SYSTEM_SPECIALLISM;
            }
            set
            {
                this.OnSYSTEM_SPECIALLISMChanging(value);
                this.ReportPropertyChanging("SYSTEM_SPECIALLISM");
                this._SYSTEM_SPECIALLISM = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SYSTEM_SPECIALLISM");
                this.OnSYSTEM_SPECIALLISMChanged();
            }
        }
        private long _SYSTEM_SPECIALLISM;
        partial void OnSYSTEM_SPECIALLISMChanging(long value);
        partial void OnSYSTEM_SPECIALLISMChanged();
        /// <summary>
        /// There are no comments for Property EXPERIENCE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long EXPERIENCE
        {
            get
            {
                return this._EXPERIENCE;
            }
            set
            {
                this.OnEXPERIENCEChanging(value);
                this.ReportPropertyChanging("EXPERIENCE");
                this._EXPERIENCE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EXPERIENCE");
                this.OnEXPERIENCEChanged();
            }
        }
        private long _EXPERIENCE;
        partial void OnEXPERIENCEChanging(long value);
        partial void OnEXPERIENCEChanged();
        /// <summary>
        /// There are no comments for Property MAX_NUMBER in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long MAX_NUMBER
        {
            get
            {
                return this._MAX_NUMBER;
            }
            set
            {
                this.OnMAX_NUMBERChanging(value);
                this.ReportPropertyChanging("MAX_NUMBER");
                this._MAX_NUMBER = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MAX_NUMBER");
                this.OnMAX_NUMBERChanged();
            }
        }
        private long _MAX_NUMBER;
        partial void OnMAX_NUMBERChanging(long value);
        partial void OnMAX_NUMBERChanged();
    }
    /// <summary>
    /// There are no comments for HeXnaModel.HEX in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="HEX")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class HEX : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new HEX object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="x">Initial value of X.</param>
        /// <param name="y">Initial value of Y.</param>
        /// <param name="tERRAIN_ID">Initial value of TERRAIN_ID.</param>
        public static HEX CreateHEX(long id, long x, long y, long tERRAIN_ID)
        {
            HEX hEX = new HEX();
            hEX.ID = id;
            hEX.X = x;
            hEX.Y = y;
            hEX.TERRAIN_ID = tERRAIN_ID;
            return hEX;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property X in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long X
        {
            get
            {
                return this._X;
            }
            set
            {
                this.OnXChanging(value);
                this.ReportPropertyChanging("X");
                this._X = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("X");
                this.OnXChanged();
            }
        }
        private long _X;
        partial void OnXChanging(long value);
        partial void OnXChanged();
        /// <summary>
        /// There are no comments for Property Y in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Y
        {
            get
            {
                return this._Y;
            }
            set
            {
                this.OnYChanging(value);
                this.ReportPropertyChanging("Y");
                this._Y = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Y");
                this.OnYChanged();
            }
        }
        private long _Y;
        partial void OnYChanging(long value);
        partial void OnYChanged();
        /// <summary>
        /// There are no comments for Property TERRAIN_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long TERRAIN_ID
        {
            get
            {
                return this._TERRAIN_ID;
            }
            set
            {
                this.OnTERRAIN_IDChanging(value);
                this.ReportPropertyChanging("TERRAIN_ID");
                this._TERRAIN_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TERRAIN_ID");
                this.OnTERRAIN_IDChanged();
            }
        }
        private long _TERRAIN_ID;
        partial void OnTERRAIN_IDChanging(long value);
        partial void OnTERRAIN_IDChanged();
        /// <summary>
        /// There are no comments for Property HEIGHT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> HEIGHT
        {
            get
            {
                return this._HEIGHT;
            }
            set
            {
                this.OnHEIGHTChanging(value);
                this.ReportPropertyChanging("HEIGHT");
                this._HEIGHT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HEIGHT");
                this.OnHEIGHTChanged();
            }
        }
        private global::System.Nullable<long> _HEIGHT;
        partial void OnHEIGHTChanging(global::System.Nullable<long> value);
        partial void OnHEIGHTChanged();
        /// <summary>
        /// There are no comments for MAP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HeXnaModel", "MAPHEX", "MAP")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public MAP MAP
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MAP>("HeXnaModel.MAPHEX", "MAP").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MAP>("HeXnaModel.MAPHEX", "MAP").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for MAP in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<MAP> MAPReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MAP>("HeXnaModel.MAPHEX", "MAP");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<MAP>("HeXnaModel.MAPHEX", "MAP", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HeXnaModel.LNK_SYSTEM_WEAPON in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="LNK_SYSTEM_WEAPON")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LNK_SYSTEM_WEAPON : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LNK_SYSTEM_WEAPON object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="sYSTEM_ID">Initial value of SYSTEM_ID.</param>
        /// <param name="wEAPON_ID">Initial value of WEAPON_ID.</param>
        public static LNK_SYSTEM_WEAPON CreateLNK_SYSTEM_WEAPON(long id, long sYSTEM_ID, long wEAPON_ID)
        {
            LNK_SYSTEM_WEAPON lNK_SYSTEM_WEAPON = new LNK_SYSTEM_WEAPON();
            lNK_SYSTEM_WEAPON.ID = id;
            lNK_SYSTEM_WEAPON.SYSTEM_ID = sYSTEM_ID;
            lNK_SYSTEM_WEAPON.WEAPON_ID = wEAPON_ID;
            return lNK_SYSTEM_WEAPON;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SYSTEM_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SYSTEM_ID
        {
            get
            {
                return this._SYSTEM_ID;
            }
            set
            {
                this.OnSYSTEM_IDChanging(value);
                this.ReportPropertyChanging("SYSTEM_ID");
                this._SYSTEM_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SYSTEM_ID");
                this.OnSYSTEM_IDChanged();
            }
        }
        private long _SYSTEM_ID;
        partial void OnSYSTEM_IDChanging(long value);
        partial void OnSYSTEM_IDChanged();
        /// <summary>
        /// There are no comments for Property WEAPON_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long WEAPON_ID
        {
            get
            {
                return this._WEAPON_ID;
            }
            set
            {
                this.OnWEAPON_IDChanging(value);
                this.ReportPropertyChanging("WEAPON_ID");
                this._WEAPON_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WEAPON_ID");
                this.OnWEAPON_IDChanged();
            }
        }
        private long _WEAPON_ID;
        partial void OnWEAPON_IDChanging(long value);
        partial void OnWEAPON_IDChanged();
    }
    /// <summary>
    /// There are no comments for HeXnaModel.LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="tERRAIN_ID">Initial value of TERRAIN_ID.</param>
        /// <param name="sYSTEM_TYPE_ID">Initial value of SYSTEM_TYPE_ID.</param>
        public static LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT CreateLNK_TERRAIN_SYSTEM_TYPE_MOVEMENT(long id, long tERRAIN_ID, long sYSTEM_TYPE_ID)
        {
            LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT lNK_TERRAIN_SYSTEM_TYPE_MOVEMENT = new LNK_TERRAIN_SYSTEM_TYPE_MOVEMENT();
            lNK_TERRAIN_SYSTEM_TYPE_MOVEMENT.ID = id;
            lNK_TERRAIN_SYSTEM_TYPE_MOVEMENT.TERRAIN_ID = tERRAIN_ID;
            lNK_TERRAIN_SYSTEM_TYPE_MOVEMENT.SYSTEM_TYPE_ID = sYSTEM_TYPE_ID;
            return lNK_TERRAIN_SYSTEM_TYPE_MOVEMENT;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property TERRAIN_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long TERRAIN_ID
        {
            get
            {
                return this._TERRAIN_ID;
            }
            set
            {
                this.OnTERRAIN_IDChanging(value);
                this.ReportPropertyChanging("TERRAIN_ID");
                this._TERRAIN_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TERRAIN_ID");
                this.OnTERRAIN_IDChanged();
            }
        }
        private long _TERRAIN_ID;
        partial void OnTERRAIN_IDChanging(long value);
        partial void OnTERRAIN_IDChanged();
        /// <summary>
        /// There are no comments for Property SYSTEM_TYPE_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SYSTEM_TYPE_ID
        {
            get
            {
                return this._SYSTEM_TYPE_ID;
            }
            set
            {
                this.OnSYSTEM_TYPE_IDChanging(value);
                this.ReportPropertyChanging("SYSTEM_TYPE_ID");
                this._SYSTEM_TYPE_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SYSTEM_TYPE_ID");
                this.OnSYSTEM_TYPE_IDChanged();
            }
        }
        private long _SYSTEM_TYPE_ID;
        partial void OnSYSTEM_TYPE_IDChanging(long value);
        partial void OnSYSTEM_TYPE_IDChanged();
        /// <summary>
        /// There are no comments for Property MOVEMENT_COST in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> MOVEMENT_COST
        {
            get
            {
                return this._MOVEMENT_COST;
            }
            set
            {
                this.OnMOVEMENT_COSTChanging(value);
                this.ReportPropertyChanging("MOVEMENT_COST");
                this._MOVEMENT_COST = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MOVEMENT_COST");
                this.OnMOVEMENT_COSTChanged();
            }
        }
        private global::System.Nullable<double> _MOVEMENT_COST;
        partial void OnMOVEMENT_COSTChanging(global::System.Nullable<double> value);
        partial void OnMOVEMENT_COSTChanged();
    }
    /// <summary>
    /// There are no comments for HeXnaModel.MAP in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="MAP")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MAP : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MAP object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        public static MAP CreateMAP(long id, string nAME)
        {
            MAP mAP = new MAP();
            mAP.ID = id;
            mAP.NAME = nAME;
            return mAP;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        private string _NAME;
        partial void OnNAMEChanging(string value);
        partial void OnNAMEChanged();
        /// <summary>
        /// There are no comments for Property DESCRIPTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION
        {
            get
            {
                return this._DESCRIPTION;
            }
            set
            {
                this.OnDESCRIPTIONChanging(value);
                this.ReportPropertyChanging("DESCRIPTION");
                this._DESCRIPTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPTION");
                this.OnDESCRIPTIONChanged();
            }
        }
        private string _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(string value);
        partial void OnDESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for HEXES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HeXnaModel", "MAPHEX", "HEX")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<HEX> HEXES
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<HEX>("HeXnaModel.MAPHEX", "HEX");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<HEX>("HeXnaModel.MAPHEX", "HEX", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HeXnaModel.SYSTEM in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="SYSTEM")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SYSTEM : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SYSTEM object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        /// <param name="sYSTEM_TYPE_ID">Initial value of SYSTEM_TYPE_ID.</param>
        /// <param name="mOVE">Initial value of MOVE.</param>
        /// <param name="fRONT_ARMOUR_MAX">Initial value of FRONT_ARMOUR_MAX.</param>
        /// <param name="fRONT_ARMOUR_MIN">Initial value of FRONT_ARMOUR_MIN.</param>
        /// <param name="rEAR_ARMOUR_MAX">Initial value of REAR_ARMOUR_MAX.</param>
        /// <param name="rEAR_ARMOUR_MIN">Initial value of REAR_ARMOUR_MIN.</param>
        /// <param name="aRMUR_PROFILE_LOCATION">Initial value of ARMUR_PROFILE_LOCATION.</param>
        /// <param name="aRMOUR_PROFILE_WEAKNESS">Initial value of ARMOUR_PROFILE_WEAKNESS.</param>
        /// <param name="fIRE_CONTROL">Initial value of FIRE_CONTROL.</param>
        /// <param name="fIRE_CONTROL_MOVEMENT_PROFILE">Initial value of FIRE_CONTROL_MOVEMENT_PROFILE.</param>
        /// <param name="lOAD_CAPACITY">Initial value of LOAD_CAPACITY.</param>
        /// <param name="sIZE">Initial value of SIZE.</param>
        public static SYSTEM CreateSYSTEM(long id, string nAME, long sYSTEM_TYPE_ID, long mOVE, long fRONT_ARMOUR_MAX, long fRONT_ARMOUR_MIN, long rEAR_ARMOUR_MAX, long rEAR_ARMOUR_MIN, double aRMUR_PROFILE_LOCATION, double aRMOUR_PROFILE_WEAKNESS, double fIRE_CONTROL, double fIRE_CONTROL_MOVEMENT_PROFILE, long lOAD_CAPACITY, long sIZE)
        {
            SYSTEM sYSTEM = new SYSTEM();
            sYSTEM.ID = id;
            sYSTEM.NAME = nAME;
            sYSTEM.SYSTEM_TYPE_ID = sYSTEM_TYPE_ID;
            sYSTEM.MOVE = mOVE;
            sYSTEM.FRONT_ARMOUR_MAX = fRONT_ARMOUR_MAX;
            sYSTEM.FRONT_ARMOUR_MIN = fRONT_ARMOUR_MIN;
            sYSTEM.REAR_ARMOUR_MAX = rEAR_ARMOUR_MAX;
            sYSTEM.REAR_ARMOUR_MIN = rEAR_ARMOUR_MIN;
            sYSTEM.ARMUR_PROFILE_LOCATION = aRMUR_PROFILE_LOCATION;
            sYSTEM.ARMOUR_PROFILE_WEAKNESS = aRMOUR_PROFILE_WEAKNESS;
            sYSTEM.FIRE_CONTROL = fIRE_CONTROL;
            sYSTEM.FIRE_CONTROL_MOVEMENT_PROFILE = fIRE_CONTROL_MOVEMENT_PROFILE;
            sYSTEM.LOAD_CAPACITY = lOAD_CAPACITY;
            sYSTEM.SIZE = sIZE;
            return sYSTEM;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        private string _NAME;
        partial void OnNAMEChanging(string value);
        partial void OnNAMEChanged();
        /// <summary>
        /// There are no comments for Property DESCRIPTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION
        {
            get
            {
                return this._DESCRIPTION;
            }
            set
            {
                this.OnDESCRIPTIONChanging(value);
                this.ReportPropertyChanging("DESCRIPTION");
                this._DESCRIPTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPTION");
                this.OnDESCRIPTIONChanged();
            }
        }
        private string _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(string value);
        partial void OnDESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for Property SYSTEM_TYPE_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SYSTEM_TYPE_ID
        {
            get
            {
                return this._SYSTEM_TYPE_ID;
            }
            set
            {
                this.OnSYSTEM_TYPE_IDChanging(value);
                this.ReportPropertyChanging("SYSTEM_TYPE_ID");
                this._SYSTEM_TYPE_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SYSTEM_TYPE_ID");
                this.OnSYSTEM_TYPE_IDChanged();
            }
        }
        private long _SYSTEM_TYPE_ID;
        partial void OnSYSTEM_TYPE_IDChanging(long value);
        partial void OnSYSTEM_TYPE_IDChanged();
        /// <summary>
        /// There are no comments for Property MOVE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long MOVE
        {
            get
            {
                return this._MOVE;
            }
            set
            {
                this.OnMOVEChanging(value);
                this.ReportPropertyChanging("MOVE");
                this._MOVE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MOVE");
                this.OnMOVEChanged();
            }
        }
        private long _MOVE;
        partial void OnMOVEChanging(long value);
        partial void OnMOVEChanged();
        /// <summary>
        /// There are no comments for Property FRONT_ARMOUR_MAX in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long FRONT_ARMOUR_MAX
        {
            get
            {
                return this._FRONT_ARMOUR_MAX;
            }
            set
            {
                this.OnFRONT_ARMOUR_MAXChanging(value);
                this.ReportPropertyChanging("FRONT_ARMOUR_MAX");
                this._FRONT_ARMOUR_MAX = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FRONT_ARMOUR_MAX");
                this.OnFRONT_ARMOUR_MAXChanged();
            }
        }
        private long _FRONT_ARMOUR_MAX;
        partial void OnFRONT_ARMOUR_MAXChanging(long value);
        partial void OnFRONT_ARMOUR_MAXChanged();
        /// <summary>
        /// There are no comments for Property FRONT_ARMOUR_MIN in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long FRONT_ARMOUR_MIN
        {
            get
            {
                return this._FRONT_ARMOUR_MIN;
            }
            set
            {
                this.OnFRONT_ARMOUR_MINChanging(value);
                this.ReportPropertyChanging("FRONT_ARMOUR_MIN");
                this._FRONT_ARMOUR_MIN = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FRONT_ARMOUR_MIN");
                this.OnFRONT_ARMOUR_MINChanged();
            }
        }
        private long _FRONT_ARMOUR_MIN;
        partial void OnFRONT_ARMOUR_MINChanging(long value);
        partial void OnFRONT_ARMOUR_MINChanged();
        /// <summary>
        /// There are no comments for Property REAR_ARMOUR_MAX in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long REAR_ARMOUR_MAX
        {
            get
            {
                return this._REAR_ARMOUR_MAX;
            }
            set
            {
                this.OnREAR_ARMOUR_MAXChanging(value);
                this.ReportPropertyChanging("REAR_ARMOUR_MAX");
                this._REAR_ARMOUR_MAX = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("REAR_ARMOUR_MAX");
                this.OnREAR_ARMOUR_MAXChanged();
            }
        }
        private long _REAR_ARMOUR_MAX;
        partial void OnREAR_ARMOUR_MAXChanging(long value);
        partial void OnREAR_ARMOUR_MAXChanged();
        /// <summary>
        /// There are no comments for Property REAR_ARMOUR_MIN in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long REAR_ARMOUR_MIN
        {
            get
            {
                return this._REAR_ARMOUR_MIN;
            }
            set
            {
                this.OnREAR_ARMOUR_MINChanging(value);
                this.ReportPropertyChanging("REAR_ARMOUR_MIN");
                this._REAR_ARMOUR_MIN = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("REAR_ARMOUR_MIN");
                this.OnREAR_ARMOUR_MINChanged();
            }
        }
        private long _REAR_ARMOUR_MIN;
        partial void OnREAR_ARMOUR_MINChanging(long value);
        partial void OnREAR_ARMOUR_MINChanged();
        /// <summary>
        /// There are no comments for Property ARMUR_PROFILE_LOCATION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double ARMUR_PROFILE_LOCATION
        {
            get
            {
                return this._ARMUR_PROFILE_LOCATION;
            }
            set
            {
                this.OnARMUR_PROFILE_LOCATIONChanging(value);
                this.ReportPropertyChanging("ARMUR_PROFILE_LOCATION");
                this._ARMUR_PROFILE_LOCATION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ARMUR_PROFILE_LOCATION");
                this.OnARMUR_PROFILE_LOCATIONChanged();
            }
        }
        private double _ARMUR_PROFILE_LOCATION;
        partial void OnARMUR_PROFILE_LOCATIONChanging(double value);
        partial void OnARMUR_PROFILE_LOCATIONChanged();
        /// <summary>
        /// There are no comments for Property ARMOUR_PROFILE_WEAKNESS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double ARMOUR_PROFILE_WEAKNESS
        {
            get
            {
                return this._ARMOUR_PROFILE_WEAKNESS;
            }
            set
            {
                this.OnARMOUR_PROFILE_WEAKNESSChanging(value);
                this.ReportPropertyChanging("ARMOUR_PROFILE_WEAKNESS");
                this._ARMOUR_PROFILE_WEAKNESS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ARMOUR_PROFILE_WEAKNESS");
                this.OnARMOUR_PROFILE_WEAKNESSChanged();
            }
        }
        private double _ARMOUR_PROFILE_WEAKNESS;
        partial void OnARMOUR_PROFILE_WEAKNESSChanging(double value);
        partial void OnARMOUR_PROFILE_WEAKNESSChanged();
        /// <summary>
        /// There are no comments for Property FIRE_CONTROL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double FIRE_CONTROL
        {
            get
            {
                return this._FIRE_CONTROL;
            }
            set
            {
                this.OnFIRE_CONTROLChanging(value);
                this.ReportPropertyChanging("FIRE_CONTROL");
                this._FIRE_CONTROL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FIRE_CONTROL");
                this.OnFIRE_CONTROLChanged();
            }
        }
        private double _FIRE_CONTROL;
        partial void OnFIRE_CONTROLChanging(double value);
        partial void OnFIRE_CONTROLChanged();
        /// <summary>
        /// There are no comments for Property FIRE_CONTROL_MOVEMENT_PROFILE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double FIRE_CONTROL_MOVEMENT_PROFILE
        {
            get
            {
                return this._FIRE_CONTROL_MOVEMENT_PROFILE;
            }
            set
            {
                this.OnFIRE_CONTROL_MOVEMENT_PROFILEChanging(value);
                this.ReportPropertyChanging("FIRE_CONTROL_MOVEMENT_PROFILE");
                this._FIRE_CONTROL_MOVEMENT_PROFILE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FIRE_CONTROL_MOVEMENT_PROFILE");
                this.OnFIRE_CONTROL_MOVEMENT_PROFILEChanged();
            }
        }
        private double _FIRE_CONTROL_MOVEMENT_PROFILE;
        partial void OnFIRE_CONTROL_MOVEMENT_PROFILEChanging(double value);
        partial void OnFIRE_CONTROL_MOVEMENT_PROFILEChanged();
        /// <summary>
        /// There are no comments for Property LOAD_CAPACITY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long LOAD_CAPACITY
        {
            get
            {
                return this._LOAD_CAPACITY;
            }
            set
            {
                this.OnLOAD_CAPACITYChanging(value);
                this.ReportPropertyChanging("LOAD_CAPACITY");
                this._LOAD_CAPACITY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LOAD_CAPACITY");
                this.OnLOAD_CAPACITYChanged();
            }
        }
        private long _LOAD_CAPACITY;
        partial void OnLOAD_CAPACITYChanging(long value);
        partial void OnLOAD_CAPACITYChanged();
        /// <summary>
        /// There are no comments for Property SIZE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SIZE
        {
            get
            {
                return this._SIZE;
            }
            set
            {
                this.OnSIZEChanging(value);
                this.ReportPropertyChanging("SIZE");
                this._SIZE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SIZE");
                this.OnSIZEChanged();
            }
        }
        private long _SIZE;
        partial void OnSIZEChanging(long value);
        partial void OnSIZEChanged();
    }
    /// <summary>
    /// There are no comments for HeXnaModel.SYSTEM_TYPE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="SYSTEM_TYPE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SYSTEM_TYPE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SYSTEM_TYPE object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        public static SYSTEM_TYPE CreateSYSTEM_TYPE(long id, string nAME)
        {
            SYSTEM_TYPE sYSTEM_TYPE = new SYSTEM_TYPE();
            sYSTEM_TYPE.ID = id;
            sYSTEM_TYPE.NAME = nAME;
            return sYSTEM_TYPE;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        private string _NAME;
        partial void OnNAMEChanging(string value);
        partial void OnNAMEChanged();
        /// <summary>
        /// There are no comments for Property DESCRIPTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION
        {
            get
            {
                return this._DESCRIPTION;
            }
            set
            {
                this.OnDESCRIPTIONChanging(value);
                this.ReportPropertyChanging("DESCRIPTION");
                this._DESCRIPTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPTION");
                this.OnDESCRIPTIONChanged();
            }
        }
        private string _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(string value);
        partial void OnDESCRIPTIONChanged();
    }
    /// <summary>
    /// There are no comments for HeXnaModel.TERRAIN in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="TERRAIN")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TERRAIN : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TERRAIN object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        public static TERRAIN CreateTERRAIN(long id, string nAME)
        {
            TERRAIN tERRAIN = new TERRAIN();
            tERRAIN.ID = id;
            tERRAIN.NAME = nAME;
            return tERRAIN;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        private string _NAME;
        partial void OnNAMEChanging(string value);
        partial void OnNAMEChanged();
    }
    /// <summary>
    /// There are no comments for HeXnaModel.UNIT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="UNIT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UNIT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UNIT object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="cREW_ID">Initial value of CREW_ID.</param>
        /// <param name="sYSTEM_ID">Initial value of SYSTEM_ID.</param>
        /// <param name="nUMBER">Initial value of NUMBER.</param>
        public static UNIT CreateUNIT(long id, long cREW_ID, long sYSTEM_ID, long nUMBER)
        {
            UNIT uNIT = new UNIT();
            uNIT.ID = id;
            uNIT.CREW_ID = cREW_ID;
            uNIT.SYSTEM_ID = sYSTEM_ID;
            uNIT.NUMBER = nUMBER;
            return uNIT;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property CREW_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long CREW_ID
        {
            get
            {
                return this._CREW_ID;
            }
            set
            {
                this.OnCREW_IDChanging(value);
                this.ReportPropertyChanging("CREW_ID");
                this._CREW_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CREW_ID");
                this.OnCREW_IDChanged();
            }
        }
        private long _CREW_ID;
        partial void OnCREW_IDChanging(long value);
        partial void OnCREW_IDChanged();
        /// <summary>
        /// There are no comments for Property SYSTEM_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SYSTEM_ID
        {
            get
            {
                return this._SYSTEM_ID;
            }
            set
            {
                this.OnSYSTEM_IDChanging(value);
                this.ReportPropertyChanging("SYSTEM_ID");
                this._SYSTEM_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SYSTEM_ID");
                this.OnSYSTEM_IDChanged();
            }
        }
        private long _SYSTEM_ID;
        partial void OnSYSTEM_IDChanging(long value);
        partial void OnSYSTEM_IDChanged();
        /// <summary>
        /// There are no comments for Property NUMBER in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long NUMBER
        {
            get
            {
                return this._NUMBER;
            }
            set
            {
                this.OnNUMBERChanging(value);
                this.ReportPropertyChanging("NUMBER");
                this._NUMBER = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NUMBER");
                this.OnNUMBERChanged();
            }
        }
        private long _NUMBER;
        partial void OnNUMBERChanging(long value);
        partial void OnNUMBERChanged();
    }
    /// <summary>
    /// There are no comments for HeXnaModel.UNIT_IN_MAP in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="UNIT_IN_MAP")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UNIT_IN_MAP : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UNIT_IN_MAP object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="uNIT_ID">Initial value of UNIT_ID.</param>
        /// <param name="hEX_ID">Initial value of HEX_ID.</param>
        /// <param name="sUPRESSION">Initial value of SUPRESSION.</param>
        /// <param name="rEADINESS">Initial value of READINESS.</param>
        public static UNIT_IN_MAP CreateUNIT_IN_MAP(long id, long uNIT_ID, long hEX_ID, long sUPRESSION, long rEADINESS)
        {
            UNIT_IN_MAP uNIT_IN_MAP = new UNIT_IN_MAP();
            uNIT_IN_MAP.ID = id;
            uNIT_IN_MAP.UNIT_ID = uNIT_ID;
            uNIT_IN_MAP.HEX_ID = hEX_ID;
            uNIT_IN_MAP.SUPRESSION = sUPRESSION;
            uNIT_IN_MAP.READINESS = rEADINESS;
            return uNIT_IN_MAP;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property UNIT_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long UNIT_ID
        {
            get
            {
                return this._UNIT_ID;
            }
            set
            {
                this.OnUNIT_IDChanging(value);
                this.ReportPropertyChanging("UNIT_ID");
                this._UNIT_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UNIT_ID");
                this.OnUNIT_IDChanged();
            }
        }
        private long _UNIT_ID;
        partial void OnUNIT_IDChanging(long value);
        partial void OnUNIT_IDChanged();
        /// <summary>
        /// There are no comments for Property HEX_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long HEX_ID
        {
            get
            {
                return this._HEX_ID;
            }
            set
            {
                this.OnHEX_IDChanging(value);
                this.ReportPropertyChanging("HEX_ID");
                this._HEX_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HEX_ID");
                this.OnHEX_IDChanged();
            }
        }
        private long _HEX_ID;
        partial void OnHEX_IDChanging(long value);
        partial void OnHEX_IDChanged();
        /// <summary>
        /// There are no comments for Property SUPRESSION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SUPRESSION
        {
            get
            {
                return this._SUPRESSION;
            }
            set
            {
                this.OnSUPRESSIONChanging(value);
                this.ReportPropertyChanging("SUPRESSION");
                this._SUPRESSION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SUPRESSION");
                this.OnSUPRESSIONChanged();
            }
        }
        private long _SUPRESSION;
        partial void OnSUPRESSIONChanging(long value);
        partial void OnSUPRESSIONChanged();
        /// <summary>
        /// There are no comments for Property READINESS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long READINESS
        {
            get
            {
                return this._READINESS;
            }
            set
            {
                this.OnREADINESSChanging(value);
                this.ReportPropertyChanging("READINESS");
                this._READINESS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("READINESS");
                this.OnREADINESSChanged();
            }
        }
        private long _READINESS;
        partial void OnREADINESSChanging(long value);
        partial void OnREADINESSChanged();
        /// <summary>
        /// There are no comments for Property REMAINING_MOVE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> REMAINING_MOVE
        {
            get
            {
                return this._REMAINING_MOVE;
            }
            set
            {
                this.OnREMAINING_MOVEChanging(value);
                this.ReportPropertyChanging("REMAINING_MOVE");
                this._REMAINING_MOVE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("REMAINING_MOVE");
                this.OnREMAINING_MOVEChanged();
            }
        }
        private global::System.Nullable<long> _REMAINING_MOVE;
        partial void OnREMAINING_MOVEChanging(global::System.Nullable<long> value);
        partial void OnREMAINING_MOVEChanged();
        /// <summary>
        /// There are no comments for Property REMAINING_ACTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> REMAINING_ACTION
        {
            get
            {
                return this._REMAINING_ACTION;
            }
            set
            {
                this.OnREMAINING_ACTIONChanging(value);
                this.ReportPropertyChanging("REMAINING_ACTION");
                this._REMAINING_ACTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("REMAINING_ACTION");
                this.OnREMAINING_ACTIONChanged();
            }
        }
        private global::System.Nullable<long> _REMAINING_ACTION;
        partial void OnREMAINING_ACTIONChanging(global::System.Nullable<long> value);
        partial void OnREMAINING_ACTIONChanged();
    }
    /// <summary>
    /// There are no comments for HeXnaModel.WEAPON in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HeXnaModel", Name="WEAPON")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class WEAPON : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new WEAPON object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        /// <param name="wEAPON_TYPE_ID">Initial value of WEAPON_TYPE_ID.</param>
        /// <param name="rANGE">Initial value of RANGE.</param>
        /// <param name="rOF">Initial value of ROF.</param>
        /// <param name="aP">Initial value of AP.</param>
        /// <param name="aP_PROFILE">Initial value of AP_PROFILE.</param>
        /// <param name="aCCURACY">Initial value of ACCURACY.</param>
        /// <param name="aCCURACY_PROFILR">Initial value of ACCURACY_PROFILR.</param>
        public static WEAPON CreateWEAPON(long id, string nAME, long wEAPON_TYPE_ID, long rANGE, long rOF, double aP, double aP_PROFILE, double aCCURACY, double aCCURACY_PROFILR)
        {
            WEAPON wEAPON = new WEAPON();
            wEAPON.ID = id;
            wEAPON.NAME = nAME;
            wEAPON.WEAPON_TYPE_ID = wEAPON_TYPE_ID;
            wEAPON.RANGE = rANGE;
            wEAPON.ROF = rOF;
            wEAPON.AP = aP;
            wEAPON.AP_PROFILE = aP_PROFILE;
            wEAPON.ACCURACY = aCCURACY;
            wEAPON.ACCURACY_PROFILR = aCCURACY_PROFILR;
            return wEAPON;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        private string _NAME;
        partial void OnNAMEChanging(string value);
        partial void OnNAMEChanged();
        /// <summary>
        /// There are no comments for Property DESCRIPTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION
        {
            get
            {
                return this._DESCRIPTION;
            }
            set
            {
                this.OnDESCRIPTIONChanging(value);
                this.ReportPropertyChanging("DESCRIPTION");
                this._DESCRIPTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPTION");
                this.OnDESCRIPTIONChanged();
            }
        }
        private string _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(string value);
        partial void OnDESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for Property WEAPON_TYPE_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long WEAPON_TYPE_ID
        {
            get
            {
                return this._WEAPON_TYPE_ID;
            }
            set
            {
                this.OnWEAPON_TYPE_IDChanging(value);
                this.ReportPropertyChanging("WEAPON_TYPE_ID");
                this._WEAPON_TYPE_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WEAPON_TYPE_ID");
                this.OnWEAPON_TYPE_IDChanged();
            }
        }
        private long _WEAPON_TYPE_ID;
        partial void OnWEAPON_TYPE_IDChanging(long value);
        partial void OnWEAPON_TYPE_IDChanged();
        /// <summary>
        /// There are no comments for Property RANGE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long RANGE
        {
            get
            {
                return this._RANGE;
            }
            set
            {
                this.OnRANGEChanging(value);
                this.ReportPropertyChanging("RANGE");
                this._RANGE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RANGE");
                this.OnRANGEChanged();
            }
        }
        private long _RANGE;
        partial void OnRANGEChanging(long value);
        partial void OnRANGEChanged();
        /// <summary>
        /// There are no comments for Property ROF in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long ROF
        {
            get
            {
                return this._ROF;
            }
            set
            {
                this.OnROFChanging(value);
                this.ReportPropertyChanging("ROF");
                this._ROF = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ROF");
                this.OnROFChanged();
            }
        }
        private long _ROF;
        partial void OnROFChanging(long value);
        partial void OnROFChanged();
        /// <summary>
        /// There are no comments for Property AP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double AP
        {
            get
            {
                return this._AP;
            }
            set
            {
                this.OnAPChanging(value);
                this.ReportPropertyChanging("AP");
                this._AP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AP");
                this.OnAPChanged();
            }
        }
        private double _AP;
        partial void OnAPChanging(double value);
        partial void OnAPChanged();
        /// <summary>
        /// There are no comments for Property AP_PROFILE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double AP_PROFILE
        {
            get
            {
                return this._AP_PROFILE;
            }
            set
            {
                this.OnAP_PROFILEChanging(value);
                this.ReportPropertyChanging("AP_PROFILE");
                this._AP_PROFILE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AP_PROFILE");
                this.OnAP_PROFILEChanged();
            }
        }
        private double _AP_PROFILE;
        partial void OnAP_PROFILEChanging(double value);
        partial void OnAP_PROFILEChanged();
        /// <summary>
        /// There are no comments for Property ACCURACY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double ACCURACY
        {
            get
            {
                return this._ACCURACY;
            }
            set
            {
                this.OnACCURACYChanging(value);
                this.ReportPropertyChanging("ACCURACY");
                this._ACCURACY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ACCURACY");
                this.OnACCURACYChanged();
            }
        }
        private double _ACCURACY;
        partial void OnACCURACYChanging(double value);
        partial void OnACCURACYChanged();
        /// <summary>
        /// There are no comments for Property ACCURACY_PROFILR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double ACCURACY_PROFILR
        {
            get
            {
                return this._ACCURACY_PROFILR;
            }
            set
            {
                this.OnACCURACY_PROFILRChanging(value);
                this.ReportPropertyChanging("ACCURACY_PROFILR");
                this._ACCURACY_PROFILR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ACCURACY_PROFILR");
                this.OnACCURACY_PROFILRChanged();
            }
        }
        private double _ACCURACY_PROFILR;
        partial void OnACCURACY_PROFILRChanging(double value);
        partial void OnACCURACY_PROFILRChanged();
    }
}
